# Generated by Django 6.0 on 2026-03-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_auto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('laptop', 'Laptop'), ('books', 'Books'), ('transport', 'Transport Support'), ('internet', 'Internet Access'), ('training', 'Training Program'), ('other', 'Other Support')], max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_allocated', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_received', to='students.student')),
                ('support_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.support')),
            ],
        ),
    ]
