# Generated by Django 6.0 on 2026-03-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_impactmetric_resourceallocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactmetric',
            name='is_auto',
        ),
    ]
