# Generated by Django 6.0 on 2026-01-11 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentors', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('weekly_checkin', 'Weekly Check-in'), ('academic', 'Academic Progress'), ('financial', 'Financial Aid Update'), ('personal', 'Personal Development'), ('attendance', 'Attendance & Engagement'), ('challenge', 'Challenges / Concerns'), ('goal', 'Goal Setting'), ('milestone', 'Milestone Achieved'), ('general', 'General Update'), ('admin', 'Admin Review')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_visible_to_student', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_notes', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mentors.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
